# Book settings
title: "From Text to Insight: Large Language Models for Materials Science Data Extraction"
author:  "Mara Wilhelmi, Martiño Ríos-García, Sherjeel Shabih, María Victoria Gil, Santiago Miret, Christoph Koch, Pepe Márquez, and Kevin Maik Jablonka"
logo: _static/images/logo.png
copyright: "2024"

latex:
  latex_documents:
    targetname: book.tex

html:
  favicon                   : "_static/images/favicon.png"  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_css:
    - custom.css
  logo:
    dark: _static/images/logo_white.png
    light: _static/images/logo.png

  # Information about where the book exists on the web
repository:
  url                       : https://github.com/lamalab-org/how-to-extract-structured-data-with-llms

launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: ""  # Binder seems to be broken often during link checks?

bibtex_bibfiles:
  - references.bib

sphinx:
  extra_extensions:
   - sphinx.ext.intersphinx
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    intersphinx_mapping:
      Python 3: ['https://docs.python.org/3/', null]
      tensorflow: ['https://www.tensorflow.org/api_docs/python', 'https://github.com/mr-ubik/tensorflow-intersphinx/raw/master/tf2_py_objects.inv']
      matplotlib [stable]: ['https://matplotlib.org/stable/', null]
      numpy [stable]: ['https://numpy.org/doc/stable/', null]
      pandas [latest?]: ['https://pandas.pydata.org/docs/', null]
      scikit-learn [stable]: ['https://scikit-learn.org/stable/', null]
      scipy [latest]: ['https://docs.scipy.org/doc/scipy/reference/', null]
      jax [latest]: ['https://jax.readthedocs.io/en/latest/', null]
      seaborn [stable]: ['https://seaborn.pydata.org/', null]
      exmol [latest]: ['https://ur-whitelab.github.io/exmol/', null]
    myst_html_meta:
      "description lang=en": "From Text to Insight: Large Language Models for Materials Science Data Extraction"
      "property=og:locale": "en_US"
      "twitter:card": "summary"
      "twitter:description": "From Text to Insight: Large Language Models for Materials Science Data Extraction"
      "twitter:title": "structmatdat.pub 📖"
      "twitter:image": "https://structmatdat.pub/_static/logo.png"
      "twitter:site": "@jablonkagroup"
    bibtex_reference_style: author_year
    bibtex_bibfiles: ["references.bib"]
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    suppress_warnings: ["mystnb.unknown_mime_type"]

execute:
  timeout: -1
  execute_notebooks: 'off'

#jupyter_execute_notebooks: force

only_build_toc_files: true
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - html_image
