[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "matextract"
version = "0.1.1"
description = "Style and Imports for the Structured Data Extraction Book"
readme = "README.md"
requires-python = ">=3.9,<3.12"
license = {text = "MIT"}
authors = [
    {name = "Mara Wilhelmi"},
    {name = "Martino Rios Garcia"},
    {name = "Sherjeel Shabih"},
    {name = "Maria Victoria Gil Matellanes"},
    {name = "Santiago Miret"},
    {name = "Christoph Koch"},
    {name = "Pepe Marquez"},
    {name = "Kevin Maik Jablonka", email = "mail@kjablonka.com"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Typing :: Typed",
]
dependencies = [
    "absl-py>=2.1.0",
    "accelerate>=0.32.1",
    "accessible-pygments>=0.0.5",
    "aiohttp>=3.9.5",
    "aiosignal>=1.3.1",
    "alabaster>=0.7.16",
    "albumentations>=1.1.0",
    "annotated-types>=0.7.0",
    "anyio>=4.4.0",
    "appdirs>=1.4.4",
    "appnope>=0.1.4",
    "argon2-cffi>=23.1.0",
    "arxiv>=2.1.3",
    "asgiref>=3.8.1",
    "async-lru>=2.0.4",
    "async-timeout>=4.0.3",
    "attrs>=23.2.0",
    "babel>=2.15.0",
    "backoff>=2.2.1",
    "bcrypt>=4.1.3",
    "beautifulsoup4>=4.12.3",
    "bert-score>=0.3.13",
    "bibtexparser>=1.4.1",
    "bitsandbytes>=0.42.0",
    "bleach>=6.1.0",
    "blinker>=1.8.2",
    "brotli>=1.1.0",
    "bs4>=0.0.2",
    "build>=1.2.1",
    "cachetools>=5.4.0",
    "certifi>=2024.7.4",
    "cffi>=1.16.0",
    "chardet>=5.2.0",
    "charset-normalizer>=3.3.2",
    "chroma-hnswlib>=0.7.5",
    "chromadb>=0.5.4",
    "click>=8.1.7",
    "colorama>=0.4.6",
    "coloredlogs>=15.0.1",
    "comm>=0.2.2",
    "configargparse>=1.7",
    "contourpy>=1.2.1",
    "crossrefapi>=1.6.0",
    "cssselect2>=0.7.0",
    "cycler>=0.12.1",
    "dataclasses-json>=0.6.7",
    "datasets>=2.20.0",
    "debugpy>=1.8.2",
    "decorator>=5.1.1",
    "deepdiff>=7.0.1",
    "defusedxml>=0.7.1",
    "deprecated>=1.2.14",
    "dill>=0.3.8",
    "diskcache>=5.6.3",
    "distro>=1.9.0",
    "dnspython>=2.6.1",
    "docstring-parser>=0.16",
    "docutils>=0.20.1",
    "easyocr>=1.7.1",
    "email-validator>=2.2.0",
    "emoji>=2.12.1",
    "et-xmlfile>=1.1.0",
    "eval-type-backport>=0.2.0",
    "evaluate>=0.4.2",
    "exceptiongroup>=1.2.2",
    "executing>=2.0.1",
    "fake-useragent>=1.5.1",
    "fastapi>=0.111.1",
    "fastapi-cli>=0.0.4",
    "fastjsonschema>=2.20.0",
    "fastprogress>=1.0.3",
    "feedparser>=6.0.11",
    "filelock>=3.15.4",
    "filetype>=1.2.0",
    "flask>=3.0.3",
    "flatbuffers>=24.3.25",
    "flexcache>=0.3",
    "flexparser>=0.3.1",
    "fonttools>=4.53.1",
    "fqdn>=1.5.1",
    "free-proxy>=1.1.1",
    "frozenlist>=1.4.1",
    "fsspec>=2024.5.0",
    "gensim>=4.3.2",
    "google-auth>=2.32.0",
    "huggingface-hub",
    "jupyter-book",
    "langchain",
    "langchain-community",
    "matplotlib",
    "numpy",
    "openai",
    "pandas",
    "pillow",
    "pytorch-lightning",
    "scikit-learn",
    "scipy",
    "torch",
    "transformers",
    "unstructured"
]

[project.urls]
Repository = "https://github.com/lamalab-org/how-to-extract-structured-data-with-llm"

[tool.hatch.build.targets.wheel]
packages = ["package/matextract"]
