name: build-and-check-book

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-build-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd package
        python -m pip  --no-cache-dir install .
        cd ..
        pip install jupyter-book
    - name: Check pre-commit
      run: |
        pip install pre-commit
        pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
    - name: Build the book
      run: jupyter-book build -n .
    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.2.0
      continue-on-error: true
      id: lc
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
          args: --verbose --exclude --max-redirects 100 --no-progress  _build/html**/*.html
