name: build-and-check-book

on:
  push:
    branches: [ main ]

jobs:
  check-build-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install -e .
        pip install jupyter-book
    - name: Build the book
      run: jupyter-book build -n .
    - name: Deploy Jupyter book to GitHub pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
        force_orphan: true
        cname: matextract.pub
