name: test-book

on:
  pull_request:
    types: [opened, reopened, edited]
  workflow_dispatch:


jobs:
  test-and-lint:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -e .
    - name: Build the book
      run: jupyter-book build -n .
